### ISSUE TITLE
Handling undefined optional fields

### ISSUE THREAD

**Issue by lindemann09** [psych-ds/validator-prototype#11]
`dataset_description.json` might comprise undefined optional fields , like  
```
{...
  "keywords": [],
  "datePublished" : "",
  "dateCreated" : "",
...}
```

I my view, this should not raise a warning.

**Comment by FelixHenninger** [comment]
Again, this is a fantastic point, thanks! I'm going to close this as a duplicate of #5 -- let's have the discussion on how to proceed over in that thread, ok?
