### ISSUE TITLE
R package: Issue inherits error message from LoadNameSpace when dplyr is not installed

### ISSUE THREAD

**Issue by pederisager** [psych-ds/validator-prototype#13]
I have installed psychds in R by running: 

`devtools::install_url(url = "https://github.com/psych-ds/validator-prototype/files/3638496/psychds_0.1.0.tar.gz")`

This automatically installs the package and the dependencies. However, if I then run `validate()` on an empty dir, the issue returned is just an error message from loadNamespace(name):

```
> psychds::validate(directory = "empty/")

  Not quite there yet! x There's a few things that we'll need you to fix.
  1 issue found in Psych-DS dataset

-- Issues ---------------------------------------------------------------------- 

Error in loadNamespace(name) : there is no package called ‘dplyr’
```

If I install `dplyr` manually the Issue text changes:

```
> psychds::validate(directory = "c:/Users/20176239/Desktop/empty/")

  Not quite there yet! x There's a few things that we'll need you to fix.
  1 issue found in Psych-DS dataset

-- Issues ---------------------------------------------------------------------- 

  dataset_description.json
    * No dataset description found
```

`dplyr` is not listed among the imports of the package. However, it certainly appears to be a dependency for the psychds package, no?

**Comment by FelixHenninger** [comment]
Hej @pederisager , thank a lot for your feedback! You're spot-on, and this is fixed in 4fea2b0da5bbcdd0fd13d8edaedee8a1da45bd02 .
